### ISSUE TITLE
Error in dependencies, and gulp

### ISSUE THREAD

**Issue by lordroseman** [saumya04/LaraAngular#1]
Hi, i found that there's and error in dependencies, some warnings about minimatch,
and deprecated dependencies, like elixir-typescript,

and when running gulp, i got error like 

````
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { target: 'es5',
  module: 'system',
  moduleResolution: 'node',
  sourceMap: true,
  emitDecoratorMetadata: true,
  experimentalDecorators: true,
  removeComments: false,
  noImplicitAny: false }
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at prefixOne (C:\app\hris\node_modules\laravel-elixir\dist\tasks\GulpPaths.js:143:43)
    at Array.map (native)
    at GulpPaths.prefix (C:\app\hris\node_modules\laravel-elixir\dist\tasks\GulpPaths.js:150:29)
    at GulpPaths.src (C:\app\hris\node_modules\laravel-elixir\dist\tasks\GulpPaths.js:44:25)
    at getPaths (C:\app\hris\node_modules\laravel-elixir-typescript\dist\index.js:44:52)
    at Function.<anonymous> (C:\app\hris\node_modules\laravel-elixir-typescript\dist\index.js:33:48)
    at Function.<anonymous> (C:\app\hris\node_modules\laravel-elixir\dist\bootstrap\EnableExtension.js:16:18)
    at mix (C:\app\hris\gulpfile.js:29:6)


````

**Comment by ariefeko** [comment]
are you solved this? I have this error too

**Comment by saumya04** [comment]
Sorry, I am no longer maintaining this repository as I don't think that merging Angular & Laravel as a single App is a better option. Instead, you should host both the frameworks on different domains to communicate with each other.
